title: Beebus' Site via GitHub Pages with Jekyll
author: Beebus
description: > # this means to ignore newlines until "baseurl:"
  Beebus' Site via GitHub Pages with Jekyll

# social links
github_username:  beebus

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
